### ISSUE TITLE
mac toolchain outdated? python3 qt5 conda

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCADMakeImage#2]
For now, i am working with my old macbook pro 2011 (high sierra). And i can't compile your branch. Is something here outdated?

`FAILED: src/Base/CMakeFiles/FreeCADBase.dir/Reader.cpp.o 
/usr/local/bin/ccache $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++  -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PP_VARIADICS=1 -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFreeCADBase_EXPORTS -DHAVE_CONFIG_H -DHAVE_SWIG=1 -DHAVE_TBB -DOCC_CONVERT_SIGNALS -DQT_CORE_LIB -DQT_NO_DEBUG -D_OCC64 -I. -I$PREFIX/cmake/../include/smesh -Isrc -I../../src -Isrc/Base -I../../src/Base -I$PREFIX/include/python3.7m -isystem $PREFIX/include/qt -isystem $PREFIX/include/qt/QtCore -isystem $PREFIX/./mkspecs/macx-clang -Wall -Wextra -Wno-write-strings -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/freecad-asm3-0.19 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Wno-undefined-var-template -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.10 -fPIC   -fPIC -std=gnu++11 -MD -MT src/Base/CMakeFiles/FreeCADBase.dir/Reader.cpp.o -MF src/Base/CMakeFiles/FreeCADBase.dir/Reader.cpp.o.d -o src/Base/CMakeFiles/FreeCADBase.dir/Reader.cpp.o -c ../../src/Base/Reader.cpp
In file included from ../../src/Base/Reader.cpp:41:
../../src/Base/Exception.h:256:23: warning: 'what' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual const char* what() const throw();
                      ^
../../src/Base/Exception.h:100:23: note: overridden virtual function is here
  virtual const char* what(void) const throw();
                      ^
../../src/Base/Exception.h:258:16: warning: 'ReportException' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void ReportException (void) const;
               ^
../../src/Base/Exception.h:103:16: note: overridden virtual function is here
  virtual void ReportException (void) const;
               ^
../../src/Base/Exception.h:262:22: warning: 'getPyObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual PyObject * getPyObject(void);
                     ^
../../src/Base/Exception.h:125:22: note: overridden virtual function is here
  virtual PyObject * getPyObject(void);
                     ^
../../src/Base/Exception.h:264:16: warning: 'setPyObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual void setPyObject( PyObject * pydict);
               ^
../../src/Base/Exception.h:127:16: note: overridden virtual function is here
  virtual void setPyObject( PyObject * pydict);
               ^
../../src/Base/Reader.cpp:639:15: error: constructor for 'Base::Reader' must explicitly initialize the base class 'std::istream' (aka 'basic_istream<char>') which does not have a default constructor
Base::Reader::Reader(const std::string& name, Base::XMLReader *parent)
              ^
$BUILD_PREFIX/bin/../include/c++/v1/istream:1642:64: note: 'std::__1::basic_istream<char>' declared here
_LIBCPP_EXTERN_TEMPLATE(class _LIBCPP_EXTERN_TEMPLATE_TYPE_VIS basic_istream<char>)
                                                               ^
4 warnings and 1 error generated.
`

**Comment by realthunder** [comment]
Please sync LinkDev and try again.

**Comment by dulouie** [comment]
LinkDev compile fine but there are some python issues on conda.

`Solving environment: | `
```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```
`failed            `                                                              

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
```

`Specifications:`

`  - freecad-asm3 -> python[version='>=3.7,<3.8.0a0']`

`Your python: python=3.8`

```
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

`The following specifications were found to be incompatible with each other:`

`Output in format: Requested package -> Available versions`

```
Package libcxxabi conflicts for:
python=3.8 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hcfea43d_1|2|3|0|4|1|hebd6815_0']
solvespace -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hcfea43d_1|2|3|0|4|1|hebd6815_0']

```

**Comment by realthunder** [comment]
Are you using my FreeCADMakeImage script to build the conda image? Anyway, the problem can be temporary solved by specifying python version in command `conda create python=3.7 ...`. Just search for this command.

**Comment by dulouie** [comment]
Thanks for your help and yes i'm using your FreeCADMakeImage script.
